# fly.toml app configuration file generated for obsidian-publish on 2026-02-17T12:21:55+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'obsidian-publish'
primary_region = 'sjc'

[build]

[env]
  DATA_DIR = '/data'
  PORT = '3000'

[[mounts]]
  source = 'publish_data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
